apiVersion: apps/v1
kind: Deployment
metadata:
  name: itiWaled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Waled-Shohdy
  template:
    metadata:
      labels:
        app: Waled-Shohdy
    spec:
      containers:
      - name: web-patient
        image: waledshohdy/waled:action 
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  type: NodePort
  selector:
    app: Waled-Shohdy
  ports:
    - port: 6000
      targetPort: 8000
      nodePort: 32000